service: fined
app: fined
org: cbeardsmore

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  apiName: ${self:service}
  stage: ${opt:stage,'dev'}
  environment:
    DYNAMODB_TABLE_FINES: ${self:service}-${self:provider.stage}-fines
    DYNAMODB_TABLE_TOKENS: ${self:service}-${self:provider.stage}-tokens
    SLACK_SIGNING_SECRET: ${ssm:/${self:service}/${self:provider.stage}/SLACK_SIGNING_SECRET~true}
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_FINES}'
  stackTags:
    PROJECT: ${self:service}

functions:
  fine:
    handler: fine.handle
    description: Fine a user a given amount.
    events:
      - http:
          path: fine
          method: post
  fines:
    handler: fines.handle
    description: List all user fines
    events:
      - http:
          path: fines
          method: post
  interaction:
    handler: interaction.handle
    description: Interactivity Endpoint for Slack Interactive Payloads
    events:
      - http:
          path: interaction
          method: post
    environment:
      BOT_ACCESS_TOKEN: ${ssm:/${self:service}/BOT_ACCESS_TOKEN~true}

resources:
  Resources:
    finesTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_FINES}
        AttributeDefinitions:
          - AttributeName: teamChannelId
            AttributeType: S
        KeySchema:
          - AttributeName: teamChannelId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    tokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_TOKENS}
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
plugins:
  - serverless-python-requirements

package:
  exclude:
    - assets/
    - local/**
    - node_modules/**
    - test/**
