service: fined
app: fined
org: cbeardsmore

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  apiName: fined
  memorySize: 512

functions:
  fine:
    handler: handler.fine
    description: Fine a user a given amount.
    events:
      - http:
        path: fine
        method: post
        private: true
  fines:
    handler: handler.fines
    description: List all user fines
    events:
      - http:
        path: fines
        method: post
        private: true
      