service: fined
app: fined
org: cbeardsmore

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  apiName: fined
  memorySize: 512
  stackTags:
    PROJECT: fined
    
functions:
  fine:
    handler: fine.handle
    description: Fine a user a given amount.
    events:
      - http:
          path: fine
          method: post
    environment:
      SLACK_SIGNING_SECRET: ${ssm:/fined/SLACK_SIGNING_SECRET~true}
  fines:
    handler: fines.handle
    description: List all user fines
    events:
      - http:
          path: fines
          method: post
    environment:
      SLACK_SIGNING_SECRET: ${ssm:/fined/SLACK_SIGNING_SECRET~true}

resources:
  Resources:
    finesTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: fines
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        